# numpy
Numpy is designed for mathematical computation.  
- Arithmetic operations  
- Statistics operations  
- Bitwise operations  
- Copying and viewing arrays  
- Searching, sorting, counting  
- Mathematical operations  
- Linear algebra  
- Broadcasting  
- Matrix operations  


## Python List vs Numpy Array

Both Python lists and Numpy arrays are ordered, mutable, and support indexing, slicing, and iterating. However, they have significant differences:

| Feature                     | Python List                          | Numpy Array                          |
|-----------------------------|---------------------------------------|---------------------------------------|
| **Data Type**               | Can hold elements of different types | Holds elements of the same type      |
| **Import Requirement**      | Built-in data structure              | Requires importing Numpy             |
| **Memory Consumption**      | Consumes more memory                 | Consumes less memory                 |
| **Resizing**                | Expands dynamically                  | Fixed size once defined              |
| **Performance**             | Slower                               | Faster                               |
| **Use Case**                | General-purpose data storage         | Mathematical and large data operations |

## Creating arrays  
np.array  
From lists, tuples  
np.arange  
np.linspace  
np.random.rand  
np.random.randint  
np.zeros => tuple as argument for multidimension  
np.ones => tuple as argument for multidimension  
np.fill  
np.full = > create one or two dimensional  
np.empty  

In [ ]:
# int8, int16, int32, int64
# uint8, uint16, uint32, uint64
# float16, float32, float64
# complex64, complex128
# bool, object, string_, unicode_

import numpy as np
nums = np.array([10, 20, 30, 40 ,50])
print(nums, nums[4], sep = '\n')
print(f"Type of nums = {nums.dtype}, Memory = {nums.nbytes}")



[10 20 30 40 50]
50
Type of nums = int64, Memory = 40


### Multidmensional array
<img src="images/m_arrays.png" width="400" height=100>

In [21]:
# Display properties and specific elements of a 2D numpy array
import numpy as np
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(nums[0, 4], nums[1, 4], sep = '\n')
print("nums.ndim = ", nums.ndim)
print("nums.shape = ", nums.shape)
print("nums.size = ", nums.size)
print("nums.itemsize = ", nums.itemsize)
print("nums.nbytes = ", nums.nbytes)

5
10
nums.ndim =  2
nums.shape =  (2, 5)
nums.size =  10
nums.itemsize =  8
nums.nbytes =  80


In [ ]:
# Display properties and specific elements of a 3D numpy array
import numpy as np
nums = np.array([[[1, 2, 3],[4, 5, 6],[15,16,17]],[[7, 8, 9],[10, 11, 12],[18,19,20]]])
print(nums)
print("nums.ndim = ", nums.ndim)
print("nums.shape = ", nums.shape)
print("nums.size = ", nums.size)
print("nums.itemsize = ", nums.itemsize)
print("nums.nbytes = ", nums.nbytes)
print(nums[0, 2, 2])

[[[ 1  2  3]
  [ 4  5  6]
  [15 16 17]]

 [[ 7  8  9]
  [10 11 12]
  [18 19 20]]]
nums.ndim =  3
nums.shape =  (2, 3, 3)
nums.size =  18
nums.itemsize =  8
nums.nbytes =  144
17


In [36]:
# Display properties and specific elements of a 4D numpy array
import numpy as np
nums = np.array([[[[1,2],[5,6]]],[[[3,4],[7,8]]]])
print(nums)
print("nums.ndim = ", nums.ndim)
print("nums.shape = ", nums.shape)
print("nums.size = ", nums.size)
print("nums.itemsize = ", nums.itemsize)
print("nums.nbytes = ", nums.nbytes)
print(nums[0,0,1,1])
nums

[[[[1 2]
   [5 6]]]


 [[[3 4]
   [7 8]]]]
nums.ndim =  4
nums.shape =  (2, 1, 2, 2)
nums.size =  8
nums.itemsize =  8
nums.nbytes =  64
6


array([[[[1, 2],
         [5, 6]]],


       [[[3, 4],
         [7, 8]]]])

In [ ]:
# Convert a list and a tuple into numpy arrays. The data type of the resulting arrays is determined by the most general type in the input.
import numpy as np
my_list=[1,2,3,4,5,6,7,8,9,10]
nums = np.array(my_list)
print(nums)
my_tuple=(1,2,3,4,5,6,7,8,9,10)
nums1 = np.array(my_tuple)
print(nums1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [44]:
# np.arange generates values within a given range with a specified step, while np.linspace generates a specified number of evenly spaced **points** within a range.
import numpy as np
int_array = np.arange(10)
print(int_array)
int_array = np.arange(100,130)
print(int_array)
int_array = np.arange(100,151,5)
print(int_array)
floats_array = np.linspace(0, 1, 5)
print(floats_array)

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129]
[100 105 110 115 120 125 130 135 140 145 150]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# np.random.rand generates random numbers in the range [0.0, 1.0). The shape of the output array is specified as an argument.
import numpy as np
my_rand_array = np.random.rand(10)
print(my_rand_array)
my_rand_array = np.random.rand(3,3)
print(my_rand_array)

[0.30865829 0.52352477 0.22291242 0.02940609 0.98984509 0.16789431
 0.59445177 0.55459611 0.76467105 0.4300737 ]
[[0.43925017 0.33489918 0.67610222]
 [0.59995064 0.107842   0.4409852 ]
 [0.84507341 0.79815783 0.01811547]]


In [49]:
import numpy as np
my_random_int_array = np.random.randint(0,10,2)
my_random_int_array

array([0, 3])

In [53]:
my_array=np.empty(10, dtype=int)
my_array.fill(5)
my_array
my_array=np.full(10, 5, dtype=int)
my_array
my_array=np.full((2,3), 5, dtype=int)
my_array

array([[5, 5, 5],
       [5, 5, 5]])

<img src="images/shape_size.png" width="400" height=200>

In [60]:
my_sec_arr = np.linspace((100,200,30),(10,20,40),10)
my_sec_arr

array([[100.        , 200.        ,  30.        ],
       [ 90.        , 180.        ,  31.11111111],
       [ 80.        , 160.        ,  32.22222222],
       [ 70.        , 140.        ,  33.33333333],
       [ 60.        , 120.        ,  34.44444444],
       [ 50.        , 100.        ,  35.55555556],
       [ 40.        ,  80.        ,  36.66666667],
       [ 30.        ,  60.        ,  37.77777778],
       [ 20.        ,  40.        ,  38.88888889],
       [ 10.        ,  20.        ,  40.        ]])

## Manipulate arrays
insert, append, delete, sort  
copy, view, base  
np.reshape, flattening (reshape(arr, -1))  
np.flatten => creates copy  
ravel => creates a view => memory efficient  
Indexing and slicing => -1 for reverse indexing  
Concatenate, stack, hstack, vstack  
split, array_split, hsplit, vsplit

In [71]:
import numpy as np
my_a = np.array([1,2,3,4,5], dtype=np.int8)
my_a = np.insert(my_a, 2, 10)
print(my_a)
my_a = np.append(my_a, [999,998])
print(my_a)
my_a = np.delete(my_a, 5)
print(my_a)
my_a = np.sort(my_a)
print(my_a)
my_2_a = np.array([[3,2,1],[4,5,6],[77,8,999]])
my_2_a = np.sort(my_2_a)
print(my_2_a)


[ 1  2 10  3  4  5]
[  1   2  10   3   4   5 999 998]
[  1   2  10   3   4 999 998]
[  1   2   3   4  10 998 999]
[[  1   2   3]
 [  4   5   6]
 [  8  77 999]]


In [ ]:
# Assignments do not copy the array, but rather create a reference to the original array. This means that if you modify the new array, the original array will also be modified.
import numpy as np
my_array = np.array([1,2,3,4,5])
my_array2 = my_array
my_array2[0] = 100
print(my_array)
# To create a copy of the array, use the copy() method.
print("***"*6)
my_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
my_array3=my_array.copy()
print("my_array = \n",my_array)
print("my_array3 = \n", my_array3)
my_array3[0, 1, 0] = 200
print("my_array = \n",my_array)
print("my_array3 = \n", my_array3)
print(f"id(my_array) = {id(my_array)}, id(my_array3) = {id(my_array3)}")
# deepcopy is same as copy in this case


[100   2   3   4   5]
******************
my_array = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
my_array3 = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
my_array = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
my_array3 = 
 [[[  1   2   3]
  [200   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]
id(my_array) = 4454941488, id(my_array3) = 4454941104


In [89]:
import numpy as np
f_arr = np.arange(1,13)
print("f_arr = \n" ,f_arr)
f_arr = f_arr.reshape(3,4)
print("f_arr = \n" ,f_arr)
f_arr = f_arr.reshape(2,2,3)
print("f_arr = \n" ,f_arr)
f_arr = np.reshape(f_arr, (4,3))
print("f_arr = \n" ,f_arr)

f_arr = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
f_arr = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f_arr = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
f_arr = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [93]:
import numpy as np
my_arr = np.reshape(np.arange(12), (3,4))
print(my_arr)
print(my_arr[1,3])
print(my_arr[2])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
[ 8  9 10 11]


In [99]:
import numpy as np
my_array = np.reshape(np.arange(1,13), (3,4))
print(my_array)
print(my_array[1:,1:])
print(my_array[1,:])
print(my_array[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7  8]
 [10 11 12]]
[5 6 7 8]
[ 3  7 11]


In [110]:
import numpy as np
f_arr = np.reshape(np.arange(1,11), (2,5))
s_arr = np.reshape(np.arange(21,31), (2,5))
print(f_arr)
print(s_arr)
print(np.concatenate((f_arr, s_arr), axis=0))
print(np.concatenate((f_arr, s_arr), axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]]


In [114]:
import numpy as np
my_array1 = np.array([1,2,3,4,5])
my_array2 = np.array([6,7,8,9,10])
my_array3 = np.stack((my_array1, my_array2))
print(my_array3)
my_array4 = np.vstack((my_array1, my_array2))
print(my_array4)
my_array5 = np.hstack((my_array1, my_array2))
print(my_array5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


### Operations
