# numpy
Numpy is designed for mathematical computation.  
- Arithmetic operations  
- Statistics operations  
- Bitwise operations  
- Copying and viewing arrays  
- Searching, sorting, counting  
- Mathematical operations  
- Linear algebra  
- Broadcasting  
- Matrix operations  


## Python List vs Numpy Array

Both Python lists and Numpy arrays are ordered, mutable, and support indexing, slicing, and iterating. However, they have significant differences:

| Feature                     | Python List                          | Numpy Array                          |
|-----------------------------|---------------------------------------|---------------------------------------|
| **Data Type**               | Can hold elements of different types | Holds elements of the same type      |
| **Import Requirement**      | Built-in data structure              | Requires importing Numpy             |
| **Memory Consumption**      | Consumes more memory                 | Consumes less memory                 |
| **Resizing**                | Expands dynamically                  | Fixed size once defined              |
| **Performance**             | Slower                               | Faster                               |
| **Use Case**                | General-purpose data storage         | Mathematical and large data operations |

## Creating arrays  
1. np.array() => create arrays from lists, tuples  
2. np.arange() => " A Range" to return evenly spaced elements => start, stop, step  
3. np.linspace() => Returns numbers which are evenly distributed with respect to interval. => start, stop, num => start and stop both are included => step = ``` (stop - start) / (total_elements -1)```  
4. np.zeros() => tuple as argument for multidimension => parameters => shape : no. of rows and columns, dtype : data type of elements (default float)   
5. np.ones() => tuple as argument for multidimension => parameters => same structure as zeros()
6. np.empty()  
7. np.eye() => identity matrix => returns a matrix with ones on the diagonal and zeros elsewhere => parameters => n : no. of rows and columns, dtype : data type of matrix elements  
8. np.random.rand()    
9. np.random.randint()    
10. np.fill()    
11. np.full()   = > create one or two dimensional  

In [9]:
# int8, int16, int32, int64
# uint8, uint16, uint32, uint64
# float16, float32, float64
# complex64, complex128
# bool, object, string_, unicode_

import numpy as np
nums = np.array([10, 20, 30, 40 ,50])
nums1 = np.array((10, 20, 30, 40 ,50))
print(nums, nums[4], sep = '\n')
print(f"Type of nums = {type(nums)}, type of nums1 = {type(nums1)}")
print(f"Type of elements in nums = {nums.dtype}, Memory = {nums.nbytes}")

[10 20 30 40 50]
50
Type of nums = <class 'numpy.ndarray'>, type of nums1 = <class 'numpy.ndarray'>
Type of elements in nums = int64, Memory = 40


### Multidmensional array
<img src="images/m_arrays.png" width="400" height=100>

In [10]:
# Display properties and specific elements of a 2D numpy array
import numpy as np
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(nums)
print(f"type(nums) = {type(nums)}")
print(f"type of elements in nums = {nums.dtype}")
print(nums[0, 3], nums[1, 4], sep = '\n')
print("nums.ndim = ", nums.ndim)
print("nums.shape = ", nums.shape)
print("nums.size = ", nums.size)
print("nums.itemsize = ", nums.itemsize)
print("nums.nbytes = ", nums.nbytes)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
type(nums) = <class 'numpy.ndarray'>
type of elements in nums = int64
4
10
nums.ndim =  2
nums.shape =  (2, 5)
nums.size =  10
nums.itemsize =  8
nums.nbytes =  80


In [29]:
# Display properties and specific elements of a 3D numpy array
import numpy as np
nums = np.array([[[1, 2, 3],[4, 5, 6],[15,16,17]],[[7, 8, 9],[10, 11, 12],[18,19,20]]])
print(nums)
print("nums.ndim = ", nums.ndim)
print("nums.shape = ", nums.shape)
print("nums.size = ", nums.size)
print("nums.itemsize = ", nums.itemsize)
print("nums.nbytes = ", nums.nbytes)
print(nums[0, 2, 2])

[[[ 1  2  3]
  [ 4  5  6]
  [15 16 17]]

 [[ 7  8  9]
  [10 11 12]
  [18 19 20]]]
nums.ndim =  3
nums.shape =  (2, 3, 3)
nums.size =  18
nums.itemsize =  8
nums.nbytes =  144
17


In [36]:
# Display properties and specific elements of a 4D numpy array
import numpy as np
nums = np.array([[[[1,2],[5,6]]],[[[3,4],[7,8]]]])
print(nums)
print("nums.ndim = ", nums.ndim)
print("nums.shape = ", nums.shape)
print("nums.size = ", nums.size)
print("nums.itemsize = ", nums.itemsize)
print("nums.nbytes = ", nums.nbytes)
print(nums[0,0,1,1])
nums

[[[[1 2]
   [5 6]]]


 [[[3 4]
   [7 8]]]]
nums.ndim =  4
nums.shape =  (2, 1, 2, 2)
nums.size =  8
nums.itemsize =  8
nums.nbytes =  64
6


array([[[[1, 2],
         [5, 6]]],


       [[[3, 4],
         [7, 8]]]])

In [37]:
# Convert a list and a tuple into numpy arrays. The data type of the resulting arrays is determined by the most general type in the input.
import numpy as np
my_list=[1,2,3,4,5,6,7,8,9,10]
nums = np.array(my_list)
print(nums)
my_tuple=(1,2,3,4,5,6,7,8,9,10)
nums1 = np.array(my_tuple)
print(nums1)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# np.arange generates values within a given range with a specified step, while np.linspace generates a specified number of evenly spaced **points** within a range.
import numpy as np
int_array = np.arange(10)
print(int_array)
int_array = np.arange(100,130)
print(int_array)
int_array = np.arange(100,151,5)
print(int_array)
# linspace
floats_array = np.linspace(0, 1, 5)
print(floats_array)
arr_from_linspace = np.linspace(0, 2, 2)
print(arr_from_linspace)

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129]
[100 105 110 115 120 125 130 135 140 145 150]
[0.   0.25 0.5  0.75 1.  ]
[0. 2.]


In [25]:
vec = np.zeros([2, 3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_from_zeroes = np.zeros((2, 3), np.int64)  # Creates a 2D array of zeros with shape (2, 3). Can also use [2, 3]
print(arr_from_zeroes)
arr_from_ones = np.ones((2, 3), np.int64)  # Creates a 2D array of ones with shape (2, 3)
print(arr_from_ones)
arr_from_empty = np.empty((2, 3), np.int64)
print(arr_from_empty)
arr_from_eye = np.eye(3, 4)  # Creates a 2D identity matrix with shape (3, 4)
print(arr_from_eye)


[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
# np.random.rand generates random numbers in the range [0.0, 1.0). The shape of the output array is specified as an argument.
import numpy as np
my_rand_array = np.random.rand(10)
print(my_rand_array)
my_rand_array = np.random.rand(3,3)
print(my_rand_array)

[0.30865829 0.52352477 0.22291242 0.02940609 0.98984509 0.16789431
 0.59445177 0.55459611 0.76467105 0.4300737 ]
[[0.43925017 0.33489918 0.67610222]
 [0.59995064 0.107842   0.4409852 ]
 [0.84507341 0.79815783 0.01811547]]


In [49]:
import numpy as np
my_random_int_array = np.random.randint(0,10,2)
my_random_int_array

array([0, 3])

In [53]:
my_array=np.empty(10, dtype=int)
my_array.fill(5)
my_array
my_array=np.full(10, 5, dtype=int)
my_array
my_array=np.full((2,3), 5, dtype=int)
my_array

array([[5, 5, 5],
       [5, 5, 5]])

<img src="images/shape_size.png" width="400" height=200>

In [60]:
my_sec_arr = np.linspace((100,200,30),(10,20,40),10)
my_sec_arr

array([[100.        , 200.        ,  30.        ],
       [ 90.        , 180.        ,  31.11111111],
       [ 80.        , 160.        ,  32.22222222],
       [ 70.        , 140.        ,  33.33333333],
       [ 60.        , 120.        ,  34.44444444],
       [ 50.        , 100.        ,  35.55555556],
       [ 40.        ,  80.        ,  36.66666667],
       [ 30.        ,  60.        ,  37.77777778],
       [ 20.        ,  40.        ,  38.88888889],
       [ 10.        ,  20.        ,  40.        ]])

## Manipulate arrays
1. insert, append, delete, sort  
2. copy, view, base  
3. np.reshape(), flattening (reshape(arr, -1)) => shape of an array means number of elements and dimensions of the array. => parameters => shape : a tuple of new shape
4. np.flatten => creates copy  
5. ravel => creates a view => memory efficient  
6. Indexing and slicing => -1 for reverse indexing  
7. Concatenate, stack, hstack, vstack  
8. split, array_split, hsplit, vsplit

In [37]:
import numpy as np
my_a = np.array([1,2,3,4,5], dtype=np.int8)
my_a = np.insert(my_a, 2, 10)
print(my_a)
my_a = np.append(my_a, [999,998])
print(my_a)
my_a = np.delete(my_a, 5)
print(my_a)
my_a = np.sort(my_a)
print(my_a)
my_2_a = np.array([[3,2,1],[4,5,6],[77,8,999]])
my_2_a = np.sort(my_2_a)
print(my_2_a)


[ 1  2 10  3  4  5]
[  1   2  10   3   4   5 999 998]
[  1   2  10   3   4 999 998]
[  1   2   3   4  10 998 999]
[[  1   2   3]
 [  4   5   6]
 [  8  77 999]]


In [38]:
# Assignments do not copy the array, but rather create a reference to the original array. This means that if you modify the new array, the original array will also be modified.
import numpy as np
my_array = np.array([1,2,3,4,5])
my_array2 = my_array
my_array2[0] = 100
print(my_array)
# To create a copy of the array, use the copy() method.
print("***"*6)
my_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
my_array3=my_array.copy()
print("my_array = \n",my_array)
print("my_array3 = \n", my_array3)
my_array3[0, 1, 0] = 200
print("my_array = \n",my_array)
print("my_array3 = \n", my_array3)
print(f"id(my_array) = {id(my_array)}, id(my_array3) = {id(my_array3)}")
# deepcopy is same as copy in this case


[100   2   3   4   5]
******************
my_array = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
my_array3 = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
my_array = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
my_array3 = 
 [[[  1   2   3]
  [200   5   6]]

 [[  7   8   9]
  [ 10  11  12]]]
id(my_array) = 4411336496, id(my_array3) = 4411332656


In [48]:
import numpy as np
f_arr = np.arange(1,13)
print("f_arr = \n" ,f_arr)
f_arr = f_arr.reshape((3,4))
print("f_arr = \n" ,f_arr)
f_arr = f_arr.reshape(2,2,3)
print("f_arr = \n" ,f_arr)
f_arr = np.reshape(f_arr, (4,3))
print("f_arr = \n" ,f_arr)

f_arr = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
f_arr = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f_arr = 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
f_arr = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
import numpy as np
my_arr = np.reshape(np.arange(12), (3,4))
print(my_arr)
print(my_arr[1,3])
print(my_arr[2])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
7
[ 8  9 10 11]


In [41]:
import numpy as np
my_array = np.reshape(np.arange(1,13), (3,4))
print(my_array)
print(my_array[1:,1:])
print(my_array[1,:])
print(my_array[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7  8]
 [10 11 12]]
[5 6 7 8]
[ 3  7 11]


In [42]:
import numpy as np
f_arr = np.reshape(np.arange(1,11), (2,5))
s_arr = np.reshape(np.arange(21,31), (2,5))
print(f_arr)
print(s_arr)
print(np.concatenate((f_arr, s_arr), axis=0))
print(np.concatenate((f_arr, s_arr), axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[ 1  2  3  4  5 21 22 23 24 25]
 [ 6  7  8  9 10 26 27 28 29 30]]


In [43]:
import numpy as np
my_array1 = np.array([1,2,3,4,5])
my_array2 = np.array([6,7,8,9,10])
my_array3 = np.stack((my_array1, my_array2))
print(my_array3)
my_array4 = np.vstack((my_array1, my_array2))
print(my_array4)
my_array5 = np.hstack((my_array1, my_array2))
print(my_array5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


### Operations
+, -, *, /, exponentiation, Specific functions to perform on them => Vectorization => Operation can be executed in parallel on multiple elements of the array. Can also use np.add(), np.subtract(), np.multiply(), np.divide(),np.mod(), np.power(), np.sqrt()  
Broadcasting  
Aggregate functions, .sum, .prod, .average, .min, .max, .mean, .std  
np.unique  
Transpose, moveaxis, swapaxes  
Reverse => slicing, flip function   



In [44]:
import numpy as np
a = np.arange(1,11)
b = np.arange(21,31)
c = np.arange(2,12)
print("a = ", a)
print("b = ",b)
print("c = ",c)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**c)
print(a//c)

a =  [ 1  2  3  4  5  6  7  8  9 10]
b =  [21 22 23 24 25 26 27 28 29 30]
c =  [ 2  3  4  5  6  7  8  9 10 11]
[22 24 26 28 30 32 34 36 38 40]
[-20 -20 -20 -20 -20 -20 -20 -20 -20 -20]
[ 21  44  69  96 125 156 189 224 261 300]
[0.04761905 0.09090909 0.13043478 0.16666667 0.2        0.23076923
 0.25925926 0.28571429 0.31034483 0.33333333]
[           1            8           81         1024        15625
       279936      5764801    134217728   3486784401 100000000000]
[0 0 0 0 0 0 0 0 0 0]


In [45]:
# Axis
import numpy as np
my_array = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[11,12,13],[14,15,16],[17,18,19]], [[21,22,23],[24,25,26],[27,28,29]]])
print("my_array = \n", my_array)
print("Shape of my_array = ", my_array.shape)

print("Sum along axis 0 = \n", np.sum(my_array, axis=0), "its shape = ", np.sum(my_array, axis=0).shape)
print("Sum along axis 1 = \n", np.sum(my_array, axis=1), "its shape = ", np.sum(my_array, axis=1).shape)
print("Sum along axis 2 = \n", np.sum(my_array, axis=2), "its shape = ", np.sum(my_array, axis=2).shape)


my_array = 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
Shape of my_array =  (3, 3, 3)
Sum along axis 0 = 
 [[33 36 39]
 [42 45 48]
 [51 54 57]] its shape =  (3, 3)
Sum along axis 1 = 
 [[12 15 18]
 [42 45 48]
 [72 75 78]] its shape =  (3, 3)
Sum along axis 2 = 
 [[ 6 15 24]
 [36 45 54]
 [66 75 84]] its shape =  (3, 3)


In [46]:
# Arithmentic operations on unequal arrays. Broadcasting is used to perform the operations.
# The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
# Subject to certian constraints, the smaller array is broadcast across the larger array so that they have compatible shapes.



In [47]:
import numpy as np
my_array1 = np.array([1,2,3,4,5,3,2,1])
my_unique_arr = np.unique(my_array1)
print(type(my_unique_arr))

my_list_from_array = my_unique_arr.tolist()
print(type(my_list_from_array), my_list_from_array)


<class 'numpy.ndarray'>
<class 'list'> [1, 2, 3, 4, 5]


## Trignometric functions, arithmetic functions
1. np.sin()  
2. np.cos()  
3. np.tan()  
4. np.exp() => e to the power of
5. np.log() => base e, np.log10(), np.log2()

6. +, -, *, /

7. @ => linear algebra matrix multiplication => also called dot product
8. Transpose of a matrix (.T), np.transpose()


In [62]:
print("sine function = ", np.sin(4))
print("cosine function = ", np.cos(4))
print("tan function = ", np.tan(4))
print("exponenetial function = ", np.exp(np.array([2, 4, 6])))
print(np.arange(5).sum())



sine function =  -0.7568024953079283
cosine function =  -0.6536436208636119
tan function =  1.1578212823495775
exponenetial function =  [  7.3890561   54.59815003 403.42879349]
10


In [69]:
matrix1 = np.arange(1, 10).reshape(3, 3)
matrix2 = np.arange(11, 20).reshape(3, 3)
print(matrix1)
print(matrix2)
print(matrix1 * matrix2)  # Element-wise multiplication
print(np.dot(matrix1, matrix2))
print(matrix1 @ matrix2)  # Matrix multiplication using the @ operator
# Transpose of a matrix
print("Transpose of matrix1 = \n", matrix1.T)
print("Transpose of matrix2 = \n", np.transpose(matrix1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
Transpose of matrix1 = 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of matrix2 = 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [67]:
arr1 = np.arange(1, 6)
arr2 = np.arange(3, 8)
print("arr1 = ", arr1)
print("arr2 = ", arr2)


print('Addition = ', arr1 + arr2)
print('Subtraction = ', arr1 - arr2)
print('Multiplication = ', arr1 * arr2)
print('Division = ', arr1 / arr2)
print('Floor Division = ', arr1 // arr2)
print('Exponentiation = ', arr1 ** arr2)
print('Modulus = ', arr1 % arr2)
print('Inverse = ', 1 / arr1)

print(arr1[::-1])

arr1 =  [1 2 3 4 5]
arr2 =  [3 4 5 6 7]
Addition =  [ 4  6  8 10 12]
Subtraction =  [-2 -2 -2 -2 -2]
Multiplication =  [ 3  8 15 24 35]
Division =  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Floor Division =  [0 0 0 0 0]
Exponentiation =  [    1    16   243  4096 78125]
Modulus =  [1 2 3 4 5]
Inverse =  [1.         0.5        0.33333333 0.25       0.2       ]
[5 4 3 2 1]


In [79]:
vec1 = np.arange(1,5).reshape(2, 2)
vec2 = np.eye(2)
print(vec1/vec2) # divide by zero gives runtime error, but the result is NaN

[[ 1. inf]
 [inf  4.]]


/var/folders/y7/j6gtt94n4n579l19ydymnm8r0000gn/T/ipykernel_58969/316845429.py:3: RuntimeWarning: divide by zero encountered in divide
  print(vec1/vec2) # divide by zero gives runtime error, but the result is NaN


## Min, Max and Random values
1. np.min()  
2. np.max()  
3. np.random.rand(d0, d1) => elements are drawn randomly from the uniform distribution over [0,1) => d0 and d1 are dimesion and d1 is optional
4. np.random.randint(low, high, size)  
5. np.random.randn(d0, d1) => n stands for normal => generates a matrix filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.  
6. np.mean(matrix), np.std(matrix)  

In [86]:
rand_mat = np.random.rand(5)
print("Random matrix = \n", rand_mat)
rand_mat = np.random.rand(5, 5)
print("Random matrix = \n", rand_mat)
rand_mat = np.random.rand(3, 3, 3)
print("Random matrix = \n", rand_mat)

Random matrix = 
 [0.95359837 0.55768402 0.17970266 0.82142854 0.05894091]
Random matrix = 
 [[0.00355022 0.55054242 0.24781546 0.49620237 0.41230635]
 [0.96796377 0.41766207 0.13985145 0.01965625 0.01633703]
 [0.56805971 0.41273559 0.53364528 0.06198364 0.89720782]
 [0.364178   0.58833801 0.69050835 0.29550126 0.3644969 ]
 [0.08218617 0.45586541 0.79745324 0.0050799  0.65955564]]
Random matrix = 
 [[[0.36576812 0.70034395 0.2714835 ]
  [0.24847908 0.96458306 0.78446271]
  [0.55692048 0.96568623 0.47357487]]

 [[0.53202699 0.34890098 0.10789222]
  [0.79808528 0.69017877 0.78243513]
  [0.04151154 0.01071074 0.75618415]]

 [[0.99676716 0.22040004 0.11048418]
  [0.902262   0.806998   0.26445521]
  [0.28771221 0.45709927 0.22588874]]]


In [87]:
mat1 = np.arange(-9, 0, 1).reshape(3, 3)
print(np.min(mat1))  
print(np.max(mat1))

-9
-1


## Accessing entries of NumPy array
Negative indexing retrieves elements from the end, and tuple indexing can access multidimesional array elements.
Logical indexing

In [102]:
rand_arry = np.random.randn(10)
print("Random array = ", rand_arry)

print(rand_arry[6])
print(rand_arry[4:9])

print('Index of value to access: ', np.arange(3, 10, 3), type(np.arange(3, 10, 3)))
print(rand_arry[np.arange(3, 10, 3)])
print(rand_arry[np.array([0, 1, 2])])
print(rand_arry[[0, 1, 2]])

print(rand_arry>0)
print('Values greater than 0: ', rand_arry[rand_arry>0])
print('Values less than 0: ', rand_arry[rand_arry<0])
print('Values between 0 and 1: ', rand_arry[(rand_arry>0) & (rand_arry<1)])
print('Values between -1 and 1: ', rand_arry[(rand_arry>-1) & (rand_arry<1)])


Random array =  [ 1.09237394  1.95450502  0.64683801  0.86909047 -0.05738265  0.35883318
 -1.01991862  2.28342399  0.17067402 -0.21087781]
-1.0199186178214832
[-0.05738265  0.35883318 -1.01991862  2.28342399  0.17067402]
Index of value to access:  [3 6 9] <class 'numpy.ndarray'>
[ 0.86909047 -1.01991862 -0.21087781]
[1.09237394 1.95450502 0.64683801]
[1.09237394 1.95450502 0.64683801]
[ True  True  True  True False  True False  True  True False]
Values greater than 0:  [1.09237394 1.95450502 0.64683801 0.86909047 0.35883318 2.28342399
 0.17067402]
Values less than 0:  [-0.05738265 -1.01991862 -0.21087781]
Values between 0 and 1:  [0.64683801 0.86909047 0.35883318 0.17067402]
Values between -1 and 1:  [ 0.64683801  0.86909047 -0.05738265  0.35883318  0.17067402 -0.21087781]


In [112]:
# access values in a matrix
rand_mat = np.random.randn(5, 5)
print("Random matrix = \n", rand_mat)

print(rand_mat[1])
print(rand_mat[1, 2], rand_mat[1] [2])  # Accessing a specific element
print(rand_mat[0:2,1:3]) # accessing first two rows with second and third column

# accessing matrices using logical indexing
sub_matrix = rand_mat[rand_mat > 0]
print(type(sub_matrix), sub_matrix.shape, sub_matrix)  # Accessing all positive values
print(rand_mat[rand_mat < 0])  # Accessing all negative values

Random matrix = 
 [[ 4.09272853e-01  2.72813285e-01 -2.33906089e-01  1.72933559e-02
   9.11640547e-01]
 [-7.34673901e-01 -2.00419127e-01 -2.54853121e-01 -8.58486142e-01
   6.46591381e-01]
 [ 1.36160081e+00  1.79255093e+00 -3.95303630e-01 -6.34402730e-01
  -1.68253426e+00]
 [-1.50064670e+00  2.20533781e+00  7.02913992e-02  1.24124682e-01
  -2.23801976e+00]
 [ 1.49802924e+00  1.95431276e+00  1.55183285e-01 -2.91221164e-01
   1.84156405e-03]]
[-0.7346739  -0.20041913 -0.25485312 -0.85848614  0.64659138]
-0.2548531211155543 -0.2548531211155543
[[ 0.27281329 -0.23390609]
 [-0.20041913 -0.25485312]]
<class 'numpy.ndarray'> (14,) [4.09272853e-01 2.72813285e-01 1.72933559e-02 9.11640547e-01
 6.46591381e-01 1.36160081e+00 1.79255093e+00 2.20533781e+00
 7.02913992e-02 1.24124682e-01 1.49802924e+00 1.95431276e+00
 1.55183285e-01 1.84156405e-03]
[-0.23390609 -0.7346739  -0.20041913 -0.25485312 -0.85848614 -0.39530363
 -0.63440273 -1.68253426 -1.5006467  -2.23801976 -0.29122116]


## Modifying entries of NumPy array